### ISSUE TITLE
ESI /search endpoint removed

### ISSUE THREAD

**Issue by nmalaguti** [antonshulgin/alice#1]
https://github.com/esi/esi-issues/blob/master/changelog.md#2022-07-12

>     REMOVAL /search
>         Use /characters/{character_id}/search instead to authenticate your search queries
>         character_id should be the ID of the character performing the query

The `/search` endpoint no longer exists and causes ` No Promise in Promise.any was resolved` when trying to look up characters.

**Comment by antonshulgin** [comment]
Should be working now. It'll now bounce you to the login screen first, then back to the app.

The new 'Reset' button will clear everything in the local storage effectively logging you out and wiping cached results.
